- name: generate /etc/dhcp/dhcpcd.conf for rpi
  template:
      src: templates/dhcpcd.conf.j2
      dest: /etc/dhcp/dhcpcd.conf
      owner: root
      group: root
      mode: 0744
  when: rpi is defined

- name: restart networking
  systemd:
    state: restarted
    name: networking
  when: rpi is defined
  ignore_errors: yes