booterizer:
  irixversion:    "6.5.22"
  installmethod:  "ftp"
  installmirror:  "https://s3.amazonaws.com"
  clientname:     "marengo"
  clientdomain:   "diller.org"
  network:        "192.168.251.0" 
  netmask:        "255.255.255.0"
  hostip:         "192.168.251.100"
  clientip:       "192.168.251.32"
  clientether:    "08:00:69:0A:9F:52"
  bridgenic:      "en0"
  myuser:         "testuser"
  myshell:        "/usr/nekoware/bin/bash"
