booterizer:
  irixversion:    "6.5.30"
  installmethod:  "ftp"
  installmirror:  "http://irix.fun/downloads"
  clientname:     "oxygen10"
  clientdomain:   "diller.org"
  network:        "192.168.251.0" 
  netmask:        "255.255.255.0"
  hostip:         "192.168.251.100"
  clientip:       "192.168.251.35"
  clientether:    "08:00:69:02:ef:e0"
  bridgenic:      "eth0"