booterizer:
  irixversion:    "5.3"
  installmethod:  "ftp"
  installmirror:  "dillernet.com"
  clientname:     "riorey"
  clientdomain:   "diller.org"
  network:        "192.168.251.0" 
  netmask:        "255.255.255.0"
  hostip:         "192.168.251.100"
  clientip:       "192.168.251.31"
  clientether:    "00:22:3F:A9:AE:4D"
  bridgenic:      "en0"