booterizer:
  singlenic:      "true"
  irixversion:    "6.5.30"
  installmethod:  "ftp"
  installmirror:  "https://s3.amazonaws.com"
  clientname:     "highstep"
  clientdomain:   "jazz.org"
  default_gw:     "192.168.0.1"
  nameserver:     "8.8.8.8"
  network:        "192.168.0.0" 
  netmask:        "255.255.255.0"
  hostip:         "192.168.0.121"
  clientip:       "192.168.0.77"
  clientether:    "08:00:69:0e:af:65"
  bridgenic:      "en0"
  myuser:         "testuser"
  myshell:        "/usr/nekoware/bin/bash"
  tzone:          "EST5EDT"