booterizer:
  installmirror:  "https://s3.amazonaws.com"
  irixversion:    "6.5.30"
  installmethod:  "ftp"
  clientname:     "sgi"
  clientdomain:   "home.local"
  network:        "192.0.2.0" 
  netmask:        "255.255.255.0"
  hostip:         "192.0.2.99"
  clientip:       "192.0.2.82"
  clientether:    "08:00:69:10:60:b0"
  bridgenic:      "eth0"
  myuser:         "testuser"
  myshell: "/usr/nekoware/bin/bash"
