booterizer:
  irixversion:    "6.5.30"
  installmethod:  "ftp"
  installmirror:  "https://s3.amazonaws.com"
  clientname:     "mycoolsgi"
  clientdomain:   "sgi.org"
  network:        "192.168.10.0" 
  netmask:        "255.255.10.0"
  hostip:         "192.168.10.41"
  clientip:       "192.168.10.42"
  clientether:    "08:00:69:0e:af:65"
  bridgenic:      "en0"
  myuser:         "testuser"
  myshell:        "/usr/nekoware/bin/bash"
