booterizer:
  installmirror:  "https://sgi-irix.s3.amazonaws.com"
  irixversion:    "6.5.30"
  installmethod:  "ftp"
  clientname:     "sgi"
  clientdomain:   "home.local"
  network:        "192.168.1.0" 
  netmask:        "255.255.255.0"
  hostip:         "192.168.1.17"
  clientip:       "192.168.1.152"
  clientether:    "08:00:69:13:68:da"
  bridgenic:      "eth0"
  myuser:         "testuser"
  myshell: "/usr/nekoware/bin/bash"
