booterizer:
  installmirror:  "https://s3.amazonaws.com"
  irixversion:    "6.5.30"
  installmethod:  "ftp"
  clientname:     "atlantis"
  clientdomain:   "devonshire.org"
  network:        "192.168.1.0"
  netmask:        "255.255.255.0"
  hostip:         "192.168.1.1"
  clientip:       "192.168.1.84"
  clientether:    "08:00:69:07:1b:9c"
  bridgenic:      "en0"
  myuser:         "testuser"
  myshell: "/usr/nekoware/bin/bash"
