- name: Install irix_ansible
  git:
    repo: 'https://github.com/docter60/irix_ansible.git'
    dest: /home/pi/{{ clientname }}
    update: yes
    clone: yes
- name: Fix repo perms
  shell: chown -R pi:pi /home/pi/{{ clientname }}/irix_ansible
  become: true
- name: Fix up inventory.yml
  template:
    src: templates/inventory.yml.j2
    dest: /home/pi/{{ clientname }}/irix_ansible/inventory.yml
    owner: pi
    group: pi
    mode: 644
