- name: Install irix_ansible
  git:
    repo: 'https://github.com/docter60/irix_ansible.git'
    dest: /home/pi/irix_ansible
    update: yes
    clone: yes
- name: Fix repo perms
  file:
    path: /home/pi/irix_ansible
    owner: pi
    group: pi
    recurse: yes
  become: true
- name: Fix up inventory.yml
  template:
    src: templates/inventory.yml.j2
    dest: /home/pi/irix_ansible/inventory.yml
    owner: pi
    group: pi
    mode: 644
