---
- name: Set up the Pi
  hosts: all
  become: yes
  tasks:
  - include_vars:
      name: settings
      file: ../settings.yml
  - import_role:
     name: rpi_setup

- name: run fetch_files role
  hosts: all
  become: yes
  tasks:
  - include_vars:
      name: settings
      file: ../settings.yml
  - include_vars:
      name: ftpurls
      file: ../irix.6.5.30.yml
    when: settings['booterizer']['irixversion'] == "6.5.30"
  - include_vars:
      name: ftpurls
      file: ../irix.6.5.22.yml
    when: settings['booterizer']['irixversion'] == "6.5.22"
  - include_vars:
      name: ftpurls
      file: ../irix.5.3.yml
    when: settings['booterizer']['irixversion'] == "5.3"
  - import_role:
     name: fetch_files
    become: true
