- name: Copy file
  copy:
    src: files/display_results.sh
    dest: /irix/display_results.sh
    owner: vagrant
    group: vagrant
    mode: 0755
- name: Copy file for pi
  copy:
    src: files/display_results.sh
    dest: /irix/display_results.sh
    owner: root
    group: root
    mode: 0744
  when: rpi is defined

- name: Display results
  command: /irix/display_results.sh
