- name: Generate selections
  template:
    src: templates/selections.j2
    dest: /irix/selections
    owner: vagrant
    group: vagrant
    mode: 0744
  when: rpi is undefined

- name: Generate selections for pi
  template:
    src: templates/selections.j2
    dest: /irix/selections
    owner: root
    group: root
    mode: 0744
  when: rpi is defined and irixversion != "5.3"

- name: Generate 5.3 selections for pi
  template:
    src: templates/selections_5.3.j2
    dest: /irix/selections
    owner: root
    group: root
    mode: 0744
  when: rpi is defined and irixversion == "5.3"
