- name: clear irix_ansible repo
  file:
    dest: /home/vagrant/irix_ansible
    state: absent
- name: Clone irix_ansible repo
  git:
    repo: 'https://github.com/unxmaal/irix_ansible.git'
    dest: /home/vagrant/irix_ansible
    update: yes
- name: create inventory.yml
  template:
    src: templates/inventory.yml.j2
    dest: /home/vagrant/irix_ansible/inventory.yml
    owner: vagrant
    group: vagrant